-- local GameOverSystem = class('GameOverSystem', System)
-- local getInput = require('helpers.getInput')
-- local loadLevel1 = require('loaders.loadLevel1')
--
-- function GameOverSystem:requires()
--   return { 'gameOver' }
-- end
--
-- function GameOverSystem:update()
--   if globalState.state == 'gameOver' and globalState.transition == 0 then
--     local downKeys = getInput()
--     if hasValue(downKeys, 'space') then
--       loadLevel1()
--     end
--   end
-- end
--
-- return GameOverSystem
